/** Generated by scripts/generate-route-catalog.mjs — do not edit. */
export const IPC_HTTP_MAP = {
  "omega:engine:command": {
    "method": "POST",
    "path": "/v1/engine/command"
  },
  "omega:inference:media:capabilities": {
    "method": "GET",
    "path": "/v1/inference/media/capabilities"
  },
  "omega:inference:media:image": {
    "method": "POST",
    "path": "/v1/inference/media/image"
  },
  "omega:inference:media:tts": {
    "method": "POST",
    "path": "/v1/inference/media/tts"
  },
  "omega:content-studio:native:render": {
    "method": "POST",
    "path": "/v1/content-studio/native/render"
  },
  "omega:config:get": {
    "method": "GET",
    "path": "/v1/config"
  },
  "omega:config:set": {
    "method": "PATCH",
    "path": "/v1/config"
  },
  "omega:model-config:get": {
    "method": "GET",
    "path": "/v1/model-config/get"
  },
  "omega:model-config:reset": {
    "method": "DELETE",
    "path": "/v1/model-config/reset"
  },
  "omega:model-config:set": {
    "method": "POST",
    "path": "/v1/model-config/set"
  },
  "omega:model-config:list": {
    "method": "GET",
    "path": "/v1/model-config/list"
  },
  "omega:model-presets:list": {
    "method": "GET",
    "path": "/v1/model-presets/list"
  },
  "omega:model-presets:apply": {
    "method": "POST",
    "path": "/v1/model-presets/apply"
  },
  "omega:runtime:status": {
    "method": "GET",
    "path": "/v1/runtime/status"
  },
  "omega:system:info": {
    "method": "GET",
    "path": "/v1/system/info"
  },
  "omega:models:list": {
    "method": "GET",
    "path": "/v1/models"
  },
  "omega:models:unload": {
    "method": "POST",
    "path": "/v1/models/unload"
  },
  "omega:models:load": {
    "method": "POST",
    "path": "/v1/models/load"
  },
  "omega:models:delete": {
    "method": "DELETE",
    "path": "/v1/models/{modelId}"
  },
  "omega:models:quantize": {
    "method": "POST",
    "path": "/v1/models/quantize"
  },
  "omega:chat:send": {
    "method": "POST",
    "path": "/v1/chat/send"
  },
  "omega:chat:abort": {
    "method": "DELETE",
    "path": "/v1/chat/abort"
  },
  "omega:chat:pick-attachments": {
    "method": "POST",
    "path": "/v1/chat/pick-attachments"
  },
  "omega:chat:stage-attachment": {
    "method": "POST",
    "path": "/v1/chat/stage-attachment"
  },
  "omega:chat:attachment-limits": {
    "method": "POST",
    "path": "/v1/chat/attachment-limits"
  },
  "omega:terminal:history": {
    "method": "GET",
    "path": "/v1/terminal/history"
  },
  "omega:terminal:clear": {
    "method": "DELETE",
    "path": "/v1/terminal/clear"
  },
  "omega:terminal:runSnippet": {
    "method": "POST",
    "path": "/v1/terminal/runSnippet"
  },
  "omega:terminal:saveSnippet": {
    "method": "POST",
    "path": "/v1/terminal/saveSnippet"
  },
  "omega:editor:read": {
    "method": "POST",
    "path": "/v1/editor/read"
  },
  "omega:editor:write": {
    "method": "POST",
    "path": "/v1/editor/write"
  },
  "omega:editor:openFiles": {
    "method": "POST",
    "path": "/v1/editor/openFiles"
  },
  "omega:editor:saveAs": {
    "method": "POST",
    "path": "/v1/editor/saveAs"
  },
  "omega:editor:deleteFile": {
    "method": "POST",
    "path": "/v1/editor/deleteFile"
  },
  "omega:agent:run": {
    "method": "POST",
    "path": "/v1/agent/run"
  },
  "omega:agent:abort": {
    "method": "DELETE",
    "path": "/v1/agent/abort"
  },
  "omega:sessions:list": {
    "method": "GET",
    "path": "/v1/sessions/list"
  },
  "omega:sessions:create": {
    "method": "POST",
    "path": "/v1/sessions/create"
  },
  "omega:sessions:delete": {
    "method": "POST",
    "path": "/v1/sessions/delete"
  },
  "omega:sessions:updateTitle": {
    "method": "POST",
    "path": "/v1/sessions/updateTitle"
  },
  "omega:sessions:updateModel": {
    "method": "POST",
    "path": "/v1/sessions/updateModel"
  },
  "omega:sessions:fork": {
    "method": "POST",
    "path": "/v1/sessions/fork"
  },
  "omega:sessions:truncate": {
    "method": "POST",
    "path": "/v1/sessions/truncate"
  },
  "omega:sessions:messages": {
    "method": "POST",
    "path": "/v1/sessions/messages"
  },
  "omega:sessions:search": {
    "method": "GET",
    "path": "/v1/sessions/search"
  },
  "omega:usage:summary": {
    "method": "GET",
    "path": "/v1/usage/summary"
  },
  "omega:workforce:agents": {
    "method": "GET",
    "path": "/v1/workforce/agents"
  },
  "omega:workforce:runs": {
    "method": "GET",
    "path": "/v1/workforce/runs"
  },
  "omega:workforce:delegate": {
    "method": "POST",
    "path": "/v1/workforce/delegate"
  },
  "omega:workforce:moa": {
    "method": "POST",
    "path": "/v1/workforce/moa"
  },
  "omega:workforce:standup": {
    "method": "POST",
    "path": "/v1/workforce/standup"
  },
  "omega:office:snapshot": {
    "method": "GET",
    "path": "/v1/office/snapshot"
  },
  "omega:office:addMonitor": {
    "method": "POST",
    "path": "/v1/office/addMonitor"
  },
  "omega:office:refreshMonitor": {
    "method": "POST",
    "path": "/v1/office/refreshMonitor"
  },
  "omega:office:fetchPr": {
    "method": "POST",
    "path": "/v1/office/fetchPr"
  },
  "omega:office:prComment": {
    "method": "POST",
    "path": "/v1/office/prComment"
  },
  "omega:office:prReview": {
    "method": "POST",
    "path": "/v1/office/prReview"
  },
  "omega:office:jiraComment": {
    "method": "POST",
    "path": "/v1/office/jiraComment"
  },
  "omega:office:pollSet": {
    "method": "POST",
    "path": "/v1/office/pollSet"
  },
  "omega:office:pollRefreshAll": {
    "method": "POST",
    "path": "/v1/office/pollRefreshAll"
  },
  "omega:office:skillGym": {
    "method": "POST",
    "path": "/v1/office/skillGym"
  },
  "omega:office:janitor": {
    "method": "POST",
    "path": "/v1/office/janitor"
  },
  "omega:office:kanbanPin": {
    "method": "POST",
    "path": "/v1/office/kanbanPin"
  },
  "omega:office:kanbanMonitor": {
    "method": "POST",
    "path": "/v1/office/kanbanMonitor"
  },
  "omega:workforce:parallel": {
    "method": "POST",
    "path": "/v1/workforce/parallel"
  },
  "omega:integrations:get": {
    "method": "GET",
    "path": "/v1/integrations/get"
  },
  "omega:integrations:set": {
    "method": "POST",
    "path": "/v1/integrations/set"
  },
  "omega:office:visualization:status": {
    "method": "GET",
    "path": "/v1/office/visualization/status"
  },
  "omega:office:visualization:setup": {
    "method": "POST",
    "path": "/v1/office/visualization/setup"
  },
  "omega:office:visualization:start": {
    "method": "POST",
    "path": "/v1/office/visualization/start"
  },
  "omega:office:visualization:stop": {
    "method": "DELETE",
    "path": "/v1/office/visualization/stop"
  },
  "omega:media:stop": {
    "method": "DELETE",
    "path": "/v1/media/stop"
  },
  "omega:media:pause": {
    "method": "POST",
    "path": "/v1/media/pause"
  },
  "omega:media:resume": {
    "method": "POST",
    "path": "/v1/media/resume"
  },
  "omega:media:showPreview": {
    "method": "POST",
    "path": "/v1/media/showPreview"
  },
  "omega:media:reopenSessionVideo": {
    "method": "POST",
    "path": "/v1/media/reopenSessionVideo"
  },
  "omega:assistant:defaultPrompt": {
    "method": "POST",
    "path": "/v1/assistant/defaultPrompt"
  },
  "omega:self-improve:list": {
    "method": "GET",
    "path": "/v1/self-improve/list"
  },
  "omega:self-improve:reflect": {
    "method": "POST",
    "path": "/v1/self-improve/reflect"
  },
  "omega:self-improve:janitor": {
    "method": "POST",
    "path": "/v1/self-improve/janitor"
  },
  "omega:updater:status": {
    "method": "GET",
    "path": "/v1/updater/status"
  },
  "omega:updater:check": {
    "method": "POST",
    "path": "/v1/updater/check"
  },
  "omega:updater:install": {
    "method": "POST",
    "path": "/v1/updater/install"
  },
  "omega:memory:list": {
    "method": "GET",
    "path": "/v1/memory/list"
  },
  "omega:memory:add": {
    "method": "POST",
    "path": "/v1/memory/add"
  },
  "omega:memory:delete": {
    "method": "DELETE",
    "path": "/v1/memory/delete"
  },
  "omega:memory:search": {
    "method": "GET",
    "path": "/v1/memory/search"
  },
  "omega:memory:graph": {
    "method": "GET",
    "path": "/v1/memory/graph"
  },
  "omega:memory:projectContext": {
    "method": "POST",
    "path": "/v1/memory/projectContext"
  },
  "omega:project:open": {
    "method": "POST",
    "path": "/v1/project/open"
  },
  "omega:project:list": {
    "method": "GET",
    "path": "/v1/project/list"
  },
  "omega:memory:export": {
    "method": "POST",
    "path": "/v1/memory/export"
  },
  "omega:memory:import": {
    "method": "POST",
    "path": "/v1/memory/import"
  },
  "omega:memory:janitorRun": {
    "method": "POST",
    "path": "/v1/memory/janitorRun"
  },
  "omega:context:buffer": {
    "method": "GET",
    "path": "/v1/context/buffer"
  },
  "omega:tools:list": {
    "method": "GET",
    "path": "/v1/tools/list"
  },
  "omega:tools:toggle": {
    "method": "POST",
    "path": "/v1/tools/toggle"
  },
  "omega:tools:run": {
    "method": "POST",
    "path": "/v1/tools/run"
  },
  "omega:tool:approve:resolve": {
    "method": "POST",
    "path": "/v1/tool/approve/resolve"
  },
  "omega:capability:permission:resolve": {
    "method": "POST",
    "path": "/v1/capability/permission/resolve"
  },
  "omega:plugins:list": {
    "method": "GET",
    "path": "/v1/plugins/list"
  },
  "omega:plugins:toggle": {
    "method": "POST",
    "path": "/v1/plugins/toggle"
  },
  "omega:plugins:reload": {
    "method": "POST",
    "path": "/v1/plugins/reload"
  },
  "omega:pipeline:activity:get": {
    "method": "GET",
    "path": "/v1/pipeline/activity/get"
  },
  "omega:models:download": {
    "method": "POST",
    "path": "/v1/models/download"
  },
  "omega:models:download-required": {
    "method": "POST",
    "path": "/v1/models/download-required"
  },
  "omega:models:download:cancel": {
    "method": "DELETE",
    "path": "/v1/models/download/cancel"
  },
  "omega:models:download-adapter": {
    "method": "POST",
    "path": "/v1/models/download-adapter"
  },
  "omega:models:check-hf-access": {
    "method": "POST",
    "path": "/v1/models/check-hf-access"
  },
  "omega:models:open-hf-repo": {
    "method": "POST",
    "path": "/v1/models/open-hf-repo"
  },
  "omega:models:repo-files": {
    "method": "POST",
    "path": "/v1/models/repo-files"
  },
  "omega:models:benchmark": {
    "method": "GET",
    "path": "/v1/models/benchmark"
  },
  "omega:models:footprint": {
    "method": "GET",
    "path": "/v1/models/footprint"
  },
  "omega:hf:search": {
    "method": "GET",
    "path": "/v1/hf/search"
  },
  "omega:hf:card": {
    "method": "GET",
    "path": "/v1/hf/card"
  },
  "omega:hf:tags": {
    "method": "GET",
    "path": "/v1/hf/tags"
  },
  "omega:gpu:list": {
    "method": "GET",
    "path": "/v1/gpu/list"
  },
  "omega:model:inspect": {
    "method": "GET",
    "path": "/v1/model/inspect"
  },
  "omega:model:estimate": {
    "method": "GET",
    "path": "/v1/model/estimate"
  },
  "omega:model:estimateFile": {
    "method": "POST",
    "path": "/v1/model/estimateFile"
  },
  "omega:skills:list": {
    "method": "GET",
    "path": "/v1/skills/list"
  },
  "omega:skills:get": {
    "method": "GET",
    "path": "/v1/skills/get"
  },
  "omega:skills:save": {
    "method": "POST",
    "path": "/v1/skills/save"
  },
  "omega:skills:delete": {
    "method": "DELETE",
    "path": "/v1/skills/delete"
  },
  "omega:skills:toggle": {
    "method": "POST",
    "path": "/v1/skills/toggle"
  },
  "omega:profiles:list": {
    "method": "GET",
    "path": "/v1/profiles/list"
  },
  "omega:profiles:create": {
    "method": "POST",
    "path": "/v1/profiles/create"
  },
  "omega:profiles:switch": {
    "method": "POST",
    "path": "/v1/profiles/switch"
  },
  "omega:profiles:delete": {
    "method": "DELETE",
    "path": "/v1/profiles/delete"
  },
  "omega:soul:get": {
    "method": "GET",
    "path": "/v1/soul/get"
  },
  "omega:soul:set": {
    "method": "POST",
    "path": "/v1/soul/set"
  },
  "omega:soul:reset": {
    "method": "DELETE",
    "path": "/v1/soul/reset"
  },
  "omega:orchestrator-prompts:defaults": {
    "method": "GET",
    "path": "/v1/orchestrator-prompts/defaults"
  },
  "omega:cron:list": {
    "method": "GET",
    "path": "/v1/cron/list"
  },
  "omega:cron:save": {
    "method": "POST",
    "path": "/v1/cron/save"
  },
  "omega:cron:delete": {
    "method": "DELETE",
    "path": "/v1/cron/delete"
  },
  "omega:cron:pause": {
    "method": "POST",
    "path": "/v1/cron/pause"
  },
  "omega:cron:runNow": {
    "method": "POST",
    "path": "/v1/cron/runNow"
  },
  "omega:kanban:list": {
    "method": "GET",
    "path": "/v1/kanban/list"
  },
  "omega:kanban:save": {
    "method": "POST",
    "path": "/v1/kanban/save"
  },
  "omega:kanban:move": {
    "method": "POST",
    "path": "/v1/kanban/move"
  },
  "omega:kanban:delete": {
    "method": "DELETE",
    "path": "/v1/kanban/delete"
  },
  "omega:kanban:dispatch": {
    "method": "POST",
    "path": "/v1/kanban/dispatch"
  },
  "omega:mcp:list": {
    "method": "GET",
    "path": "/v1/mcp/list"
  },
  "omega:mcp:save": {
    "method": "POST",
    "path": "/v1/mcp/save"
  },
  "omega:mcp:delete": {
    "method": "DELETE",
    "path": "/v1/mcp/delete"
  },
  "omega:mcp:start": {
    "method": "POST",
    "path": "/v1/mcp/start"
  },
  "omega:mcp:stop": {
    "method": "DELETE",
    "path": "/v1/mcp/stop"
  },
  "omega:mcp:status": {
    "method": "GET",
    "path": "/v1/mcp/status"
  },
  "omega:providers:list": {
    "method": "GET",
    "path": "/v1/providers/list"
  },
  "omega:providers:save": {
    "method": "POST",
    "path": "/v1/providers/save"
  },
  "omega:providers:delete": {
    "method": "DELETE",
    "path": "/v1/providers/delete"
  },
  "omega:providers:presets": {
    "method": "GET",
    "path": "/v1/providers/presets"
  },
  "omega:providers:discover": {
    "method": "POST",
    "path": "/v1/providers/discover"
  },
  "omega:providers:fetchModels": {
    "method": "POST",
    "path": "/v1/providers/fetchModels"
  },
  "omega:gateway:platforms": {
    "method": "GET",
    "path": "/v1/gateway/platforms"
  },
  "omega:gateway:list": {
    "method": "GET",
    "path": "/v1/gateway/list"
  },
  "omega:gateway:save": {
    "method": "POST",
    "path": "/v1/gateway/save"
  },
  "omega:gateway:delete": {
    "method": "DELETE",
    "path": "/v1/gateway/delete"
  },
  "omega:gateway:start": {
    "method": "POST",
    "path": "/v1/gateway/start"
  },
  "omega:gateway:stop": {
    "method": "DELETE",
    "path": "/v1/gateway/stop"
  },
  "omega:gateway:status": {
    "method": "GET",
    "path": "/v1/gateway/status"
  },
  "omega:inference:backends": {
    "method": "GET",
    "path": "/v1/inference/backends"
  },
  "omega:engines:status": {
    "method": "GET",
    "path": "/v1/engines/status"
  },
  "omega:engines:ollama:start": {
    "method": "POST",
    "path": "/v1/engines/ollama/start"
  },
  "omega:engines:ollama:stop": {
    "method": "DELETE",
    "path": "/v1/engines/ollama/stop"
  },
  "omega:engines:ollama:pull": {
    "method": "POST",
    "path": "/v1/engines/ollama/pull"
  },
  "omega:engines:ollama:list": {
    "method": "GET",
    "path": "/v1/engines/ollama/list"
  },
  "omega:engines:sidecar:status": {
    "method": "GET",
    "path": "/v1/engines/sidecar/status"
  },
  "omega:engines:sidecar:install": {
    "method": "POST",
    "path": "/v1/engines/sidecar/install"
  },
  "omega:engines:sidecar:uninstall": {
    "method": "DELETE",
    "path": "/v1/engines/sidecar/uninstall"
  },
  "omega:routerModels:status": {
    "method": "GET",
    "path": "/v1/routerModels/status"
  },
  "omega:routerModels:installNodeRuntime": {
    "method": "POST",
    "path": "/v1/routerModels/installNodeRuntime"
  },
  "omega:routerModels:setupPython": {
    "method": "POST",
    "path": "/v1/routerModels/setupPython"
  },
  "omega:routerModels:build": {
    "method": "POST",
    "path": "/v1/routerModels/build"
  },
  "omega:routerModels:remove": {
    "method": "DELETE",
    "path": "/v1/routerModels/remove"
  },
  "omega:plugins:catalog": {
    "method": "GET",
    "path": "/v1/plugins/catalog"
  },
  "omega:plugins:installBuiltin": {
    "method": "POST",
    "path": "/v1/plugins/installBuiltin"
  },
  "omega:plugins:installUrl": {
    "method": "POST",
    "path": "/v1/plugins/installUrl"
  },
  "omega:plugins:uninstall": {
    "method": "DELETE",
    "path": "/v1/plugins/uninstall"
  },
  "omega:inference:backend": {
    "method": "GET",
    "path": "/v1/inference/backend"
  },
  "omega:inference:switch": {
    "method": "POST",
    "path": "/v1/inference/switch"
  },
  "omega:debug:history": {
    "method": "GET",
    "path": "/v1/debug/history"
  },
  "omega:runtime:loaded": {
    "method": "GET",
    "path": "/v1/models/loaded"
  },
  "omega:workflows:list": {
    "method": "GET",
    "path": "/v1/workflows/list"
  },
  "omega:workflows:get": {
    "method": "GET",
    "path": "/v1/workflows/get"
  },
  "omega:workflows:save": {
    "method": "POST",
    "path": "/v1/workflows/save"
  },
  "omega:workflows:delete": {
    "method": "DELETE",
    "path": "/v1/workflows/delete"
  },
  "omega:workflows:run": {
    "method": "POST",
    "path": "/v1/workflows/run"
  },
  "omega:workflows:abort": {
    "method": "DELETE",
    "path": "/v1/workflows/abort"
  },
  "omega:input-pipelines:list": {
    "method": "GET",
    "path": "/v1/input-pipelines/list"
  },
  "omega:input-pipelines:get": {
    "method": "GET",
    "path": "/v1/input-pipelines/get"
  },
  "omega:input-pipelines:save": {
    "method": "POST",
    "path": "/v1/input-pipelines/save"
  },
  "omega:input-pipelines:delete": {
    "method": "POST",
    "path": "/v1/input-pipelines/delete"
  },
  "omega:input-pipelines:set-active": {
    "method": "POST",
    "path": "/v1/input-pipelines/set-active"
  },
  "omega:rag:list": {
    "method": "GET",
    "path": "/v1/rag/list"
  },
  "omega:rag:index-file": {
    "method": "POST",
    "path": "/v1/rag/index-file"
  },
  "omega:rag:index-dir": {
    "method": "POST",
    "path": "/v1/rag/index-dir"
  },
  "omega:rag:clear": {
    "method": "DELETE",
    "path": "/v1/rag/clear"
  },
  "omega:rag:search": {
    "method": "GET",
    "path": "/v1/rag/search"
  },
  "omega:browser:show": {
    "method": "POST",
    "path": "/v1/browser/show"
  },
  "omega:browser:hide": {
    "method": "POST",
    "path": "/v1/browser/hide"
  },
  "omega:browser:mediaCommand": {
    "method": "POST",
    "path": "/v1/browser/mediaCommand"
  },
  "omega:browser:setBounds": {
    "method": "POST",
    "path": "/v1/browser/setBounds"
  },
  "omega:browser:navigate": {
    "method": "POST",
    "path": "/v1/browser/navigate"
  },
  "omega:browser:back": {
    "method": "POST",
    "path": "/v1/browser/back"
  },
  "omega:browser:forward": {
    "method": "POST",
    "path": "/v1/browser/forward"
  },
  "omega:browser:reload": {
    "method": "POST",
    "path": "/v1/browser/reload"
  },
  "omega:browser:getStatus": {
    "method": "POST",
    "path": "/v1/browser/getStatus"
  },
  "omega:browser:info": {
    "method": "GET",
    "path": "/v1/browser/info"
  },
  "omega:finetune:analyze": {
    "method": "POST",
    "path": "/v1/finetune/analyze"
  },
  "omega:finetune:prepareDataset": {
    "method": "POST",
    "path": "/v1/finetune/prepareDataset"
  },
  "omega:finetune:list": {
    "method": "GET",
    "path": "/v1/finetune/list"
  },
  "omega:finetune:get": {
    "method": "GET",
    "path": "/v1/finetune/get"
  },
  "omega:finetune:create": {
    "method": "POST",
    "path": "/v1/finetune/create"
  },
  "omega:finetune:start": {
    "method": "POST",
    "path": "/v1/finetune/start"
  },
  "omega:finetune:abort": {
    "method": "DELETE",
    "path": "/v1/finetune/abort"
  },
  "omega:finetune:delete": {
    "method": "DELETE",
    "path": "/v1/finetune/delete"
  },
  "omega:finetune:listDatasets": {
    "method": "POST",
    "path": "/v1/finetune/listDatasets"
  },
  "omega:finetune:listPresets": {
    "method": "POST",
    "path": "/v1/finetune/listPresets"
  },
  "omega:finetune:savePreset": {
    "method": "POST",
    "path": "/v1/finetune/savePreset"
  },
  "omega:finetune:deletePreset": {
    "method": "POST",
    "path": "/v1/finetune/deletePreset"
  },
  "omega:finetune:inspectSource": {
    "method": "POST",
    "path": "/v1/finetune/inspectSource"
  },
  "omega:finetune:pickSources": {
    "method": "POST",
    "path": "/v1/finetune/pickSources"
  },
  "omega:finetune:datasetsRoot": {
    "method": "POST",
    "path": "/v1/finetune/datasetsRoot"
  },
  "omega:finetune:deletePrepared": {
    "method": "POST",
    "path": "/v1/finetune/deletePrepared"
  },
  "omega:python:status": {
    "method": "GET",
    "path": "/v1/python/status"
  },
  "omega:python:setup": {
    "method": "POST",
    "path": "/v1/python/setup"
  },
  "omega:content-studio:status": {
    "method": "GET",
    "path": "/v1/content-studio/status"
  },
  "omega:content-studio:setupEnvironment": {
    "method": "POST",
    "path": "/v1/python/setup"
  },
  "omega:content-studio:start": {
    "method": "POST",
    "path": "/v1/content-studio/start"
  },
  "omega:content-studio:stop": {
    "method": "DELETE",
    "path": "/v1/content-studio/stop"
  },
  "omega:content-studio:restart": {
    "method": "POST",
    "path": "/v1/content-studio/restart"
  },
  "omega:content-studio:projects": {
    "method": "GET",
    "path": "/v1/content-studio/projects"
  },
  "omega:content-studio:createRun": {
    "method": "POST",
    "path": "/v1/content-studio/createRun"
  },
  "omega:content-studio:runStatus": {
    "method": "POST",
    "path": "/v1/content-studio/runStatus"
  },
  "omega:content-studio:forceStopJob": {
    "method": "POST",
    "path": "/v1/content-studio/forceStopJob"
  },
  "omega:content-studio:schedules": {
    "method": "GET",
    "path": "/v1/content-studio/schedules"
  },
  "omega:content-studio:scheduleCreate": {
    "method": "POST",
    "path": "/v1/content-studio/scheduleCreate"
  },
  "omega:content-studio:scheduleDelete": {
    "method": "POST",
    "path": "/v1/content-studio/scheduleDelete"
  },
  "omega:content-studio:socialPlatforms": {
    "method": "POST",
    "path": "/v1/content-studio/socialPlatforms"
  },
  "omega:content-studio:socialAccounts": {
    "method": "POST",
    "path": "/v1/content-studio/socialAccounts"
  },
  "omega:content-studio:socialPosts": {
    "method": "POST",
    "path": "/v1/content-studio/socialPosts"
  },
  "omega:content-studio:socialPublish": {
    "method": "POST",
    "path": "/v1/content-studio/socialPublish"
  },
  "omega:content-studio:credentialsGet": {
    "method": "GET",
    "path": "/v1/content-studio/credentialsGet"
  },
  "omega:content-studio:credentialsSet": {
    "method": "POST",
    "path": "/v1/content-studio/credentialsSet"
  },
  "omega:content-studio:credentialsSync": {
    "method": "POST",
    "path": "/v1/content-studio/credentialsSync"
  },
  "omega:content-studio:credentialsStatus": {
    "method": "GET",
    "path": "/v1/content-studio/credentialsStatus"
  },
  "omega:content-studio:youtubeConnect": {
    "method": "POST",
    "path": "/v1/content-studio/youtubeConnect"
  },
  "omega:content-studio:seriesList": {
    "method": "POST",
    "path": "/v1/content-studio/seriesList"
  },
  "omega:content-studio:seriesCreate": {
    "method": "POST",
    "path": "/v1/content-studio/seriesCreate"
  },
  "omega:content-studio:seriesDelete": {
    "method": "POST",
    "path": "/v1/content-studio/seriesDelete"
  },
  "omega:content-studio:generationGet": {
    "method": "GET",
    "path": "/v1/content-studio/generationGet"
  },
  "omega:content-studio:generationSet": {
    "method": "POST",
    "path": "/v1/content-studio/generationSet"
  },
  "omega:content-studio:generationCatalog": {
    "method": "GET",
    "path": "/v1/content-studio/generationCatalog"
  },
  "omega:content-studio:generationCapabilities": {
    "method": "GET",
    "path": "/v1/content-studio/generationCapabilities"
  },
  "omega:content-studio:generationDownload": {
    "method": "POST",
    "path": "/v1/content-studio/generationDownload"
  },
  "omega:avatar-monitor:set-enabled": {
    "method": "POST",
    "path": "/v1/avatar-monitor/set-enabled"
  },
  "omega:avatar-monitor:get-enabled": {
    "method": "POST",
    "path": "/v1/avatar-monitor/get-enabled"
  },
  "omega:avatar-monitor:signals": {
    "method": "POST",
    "path": "/v1/avatar-monitor/signals"
  },
  "omega:avatar-monitor:sync-layout": {
    "method": "POST",
    "path": "/v1/avatar-monitor/sync-layout"
  },
  "omega:avatar-monitor:set-overlay-visible": {
    "method": "POST",
    "path": "/v1/avatar-monitor/set-overlay-visible"
  },
  "omega:avatar-monitor:restore-main": {
    "method": "POST",
    "path": "/v1/avatar-monitor/restore-main"
  },
  "omega:companion:set-active-chat": {
    "method": "POST",
    "path": "/v1/companion/set-active-chat"
  },
  "omega:companion:get-active-chat": {
    "method": "POST",
    "path": "/v1/companion/get-active-chat"
  },
  "omega:companion:send-to-main": {
    "method": "POST",
    "path": "/v1/companion/send-to-main"
  },
  "omega:companion:reply-broadcast": {
    "method": "POST",
    "path": "/v1/companion/reply-broadcast"
  },
  "omega:screen-snip:capture": {
    "method": "POST",
    "path": "/v1/screen-snip/capture"
  },
  "omega:screen-snip:get-bounds": {
    "method": "POST",
    "path": "/v1/screen-snip/get-bounds"
  },
  "omega:screen-snip:submit": {
    "method": "POST",
    "path": "/v1/screen-snip/submit"
  },
  "omega:screen-snip:cancel": {
    "method": "DELETE",
    "path": "/v1/screen-snip/cancel"
  },
  "omega:screen-snip:save": {
    "method": "POST",
    "path": "/v1/screen-snip/save"
  }
} as const

export type IpcHttpChannel = keyof typeof IPC_HTTP_MAP

export const IPC_EVENT_CHANNELS: readonly string[] = [
  "omega:agent:step",
  "omega:agent:token",
  "omega:avatar-monitor:enabled",
  "omega:avatar-monitor:layout",
  "omega:avatar-monitor:signals",
  "omega:browser:hidden",
  "omega:browser:status",
  "omega:capability:permission:req",
  "omega:companion:reply-deliver",
  "omega:companion:send-deliver",
  "omega:config:changed",
  "omega:content-studio:changed",
  "omega:content-studio:setupProgress",
  "omega:context:find",
  "omega:context:gotoLine",
  "omega:cron:changed",
  "omega:debug:event",
  "omega:download:progress",
  "omega:engines:ollama:pullProgress",
  "omega:engines:sidecar:installProgress",
  "omega:finetune:progress",
  "omega:gateway:statusChanged",
  "omega:kanban:changed",
  "omega:mcp:statusChanged",
  "omega:media:state",
  "omega:models:inventoryChanged",
  "omega:models:load-progress",
  "omega:office:changed",
  "omega:pipeline:activity:changed",
  "omega:providers:changed",
  "omega:quantize:progress",
  "omega:routerModels:buildProgress",
  "omega:runtime:status-changed",
  "omega:screen-snip:init",
  "omega:session:assistantPatch",
  "omega:session:messageAppended",
  "omega:shortcut",
  "omega:stream:done",
  "omega:stream:error",
  "omega:stream:media",
  "omega:stream:metrics",
  "omega:stream:token",
  "omega:terminal:line",
  "omega:tool:approve:req",
  "omega:updater:status-event",
  "omega:voice:speak",
  "omega:workflows:event"
]

export function isIpcHttpChannel(ipc: string): ipc is IpcHttpChannel {
  return ipc in IPC_HTTP_MAP
}
